apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: statusquarkusio-bc3x
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: statusquarkusio-bc3x
    app.kubernetes.io/part-of: status-quarkus-io
  name: statusquarkusio-bc3x
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: java-quarkus-app
      app.kubernetes.io/instance: statusquarkusio-bc3x
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: java-quarkus-app
        app.kubernetes.io/instance: statusquarkusio-bc3x
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/rhtap-demo-mbfr-tenant/status-quarkus-io/statusquarkusio-bc3x@sha256:09fed0c4225c2f2c11c5c511fc5327dcf21ac5c66141065748aa4c5382120b79
        name: my-java-quarkus
        ports:
        - containerPort: 8081
          name: http
          protocol: TCP
        - containerPort: 9081
        resources:
          requests:
            cpu: 10m
            memory: 100Mi
status: {}
